<a href="https://colab.research.google.com/github/mcanes76/mg-pytorch-deep-learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#00.PyTorch Fundamentals Exercises
##1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using.  We'll be using PyTorch documentation a lot throughout the rest of this course. So I'd recommend spedning 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

- The documentation on `torch.Tensor': https://pytorch.org/docs/stable/tensors.html#torch-tensor

- The documentation on 'torch.cuda': https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics

In [ ]:
# No code as the assignment is to read the documentation in the links

#2. Create a random tensor with shape (7,7)

In [5]:
# Import torch
import torch

# Create random tensor
T1_rand = torch.rand(7,7)
print(T1_rand)

tensor([[0.6645, 0.7183, 0.8554, 0.7040, 0.5511, 0.4463, 0.0911],
        [0.2174, 0.3646, 0.0917, 0.8927, 0.5832, 0.4595, 0.4348],
        [0.3601, 0.0011, 0.4529, 0.6208, 0.1518, 0.9934, 0.5268],
        [0.3578, 0.2817, 0.8870, 0.6805, 0.8788, 0.6338, 0.4643],
        [0.3128, 0.9499, 0.3349, 0.6560, 0.5388, 0.4328, 0.9804],
        [0.8186, 0.0669, 0.8932, 0.6890, 0.1348, 0.3924, 0.5374],
        [0.0077, 0.5913, 0.1057, 0.0561, 0.0583, 0.0074, 0.0239]])


#3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1,7) (hint: you may need to transpose the second tensor).

In [10]:
# Create another random tensor
T2_rand = torch.rand(1,7)
T2_rand

# Perform matrix multiplication
T3_matmult = torch.matmul(T1_rand, T2_rand.T)
T3_matmult

tensor([[1.9794],
        [1.3091],
        [1.1908],
        [1.6349],
        [2.2597],
        [1.6014],
        [0.6414]])

#4. Set the random seed to `0` and do 2 & 3 over again

The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))

In [13]:
# Set the manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

T1_randS0 = torch.rand(7,7)
print(f"T1_randS0 = {T1_randS0}")

T2_randS0 = torch.rand(1,7)
print(f"T2_randS0 = {T2_randS0}")

T3_matmultS0 = torch.matmul(T1_randS0, T2_randS0.T)
print(f"T3_matmultS0 = {T3_matmultS0}")

T1_randS0 = tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
T2_randS0 = tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])
T3_matmultS0 = tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


#5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)

- If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on GPU
import torch

RANDOM_SEED_GPU = 1234
RANDOM_SEED_CPU = 42

torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"

if torch.cuda.is_available():
  torch.manual_seed(RANDOM_SEED_GPU)
else:
  torch.use_deterministic_algorithms(True)
  torch.manual_seed(RANDOM_SEED_CPU)

print(device)
print(torch.rand(2))

cpu
tensor([0.8823, 0.9150])
